version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"  # Expose NestJS app port
    depends_on:
      - db  # Depend on the db service

  db:
    image: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
